### ISSUE TITLE
writing the report

### ISSUE THREAD

**Issue by ardalaan** [ardalaan/SE-team-10#18]
[SE team 10 phase-1.pdf](https://github.com/ardalaan/SE-team-10/files/11181523/SE.team.10.phase-1.pdf)

**Comment by RwinRad** [comment]
[report issues.pdf](https://github.com/ardalaan/SE-team-10/files/11182014/report.issues.pdf)

**Comment by ardalaan** [comment]
final version
[SE_team#10_phase1.pdf](https://github.com/ardalaan/SE-team-10/files/11182982/SE_team.10_phase1.pdf)
